# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 23:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_l1', models.CharField(max_length=46)),
                ('address_l2', models.CharField(blank=True, max_length=46, null=True)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12), blank=True, null=True, size=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(max_length=254)),
                ('twitter', models.CharField(max_length=140)),
                ('instagram', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
