# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_l1', models.CharField(max_length=46)),
                ('address_l2', models.CharField(blank=True, max_length=46, null=True)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12), blank=True, editable=False, null=True, size=2)),
                ('raw_coordinate_data', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, max_length=254, null=True)),
                ('twitter', models.CharField(blank=True, max_length=140, null=True)),
                ('instagram', models.CharField(blank=True, max_length=140, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pantry', to='pantry.Address')),
            ],
            options={
                'verbose_name_plural': 'Pantries',
            },
        ),
    ]
