# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_auto_20160321_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='raw_coordinate_data',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
